# Stage 1: Build the application
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

RUN echo "VITE_APP_TITLE=Menus" > .env.production
RUN echo "VITE_API_RELATIVE_PATH=/menus/" >> .env.production

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Serve the application with nginx
FROM nginx:alpine

# Copy the built files from the previous stage
COPY --from=builder /app/dist /usr/share/nginx/html/menus

# Copy the nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.conf /usr/share/nginx/html/nginx.conf

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]