services:
  menus-backend:
    build: ./server
    image: aureliroura/menu-server:latest
    container_name: menu-backend
    restart: always
    ports:
      - "3000:3000"
      - "3443:3443"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - MONGODB_DB=menudb
    volumes:
      - ./server/cert:/app/cert
    networks:
      - menus-network

  menus-frontend:
    build: ./frontend
    image: aureliroura/menu-frontend:latest
    container_name: menu-frontend
    restart: always
    ports:
      - "9092:80"
    depends_on:
      - menus-backend
    networks:
      - menus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  menus-network:
    driver: bridge
