
services:
  menus-backend:
    build: ./server
    image: menu-server:latest
    restart: always
    ports:
      - "3000:3000"
      - "3443:3443"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - MONGODB_DB=menudb
    volumes:
      - ./server/cert:/app/cert
    networks:
      - menus-network

  menus-frontend:
    build: ./frontend
    image: menu-frontend:latest
    ports:
      - "9092:80"
    depends_on:
      - menus-backend
    networks:
      - menus-network

networks:
  menus-network:
    driver: bridge
