# 1️⃣ Imatge base oficial de Node.js
FROM node:20-alpine AS builder

# 2️⃣ Definir el directori de treball
WORKDIR /app

# 3️⃣ Copiar només els fitxers de dependències per optimitzar la caché
COPY package*.json tsconfig.json ./

# 4️⃣ Instal·lar dependències
RUN npm ci && npm cache clean --force

# 5️⃣ Copiar el codi font
COPY ./src ./src

# 6️⃣ Compilar el codi TypeScript
RUN npm run build
ENV PATH=/usr/local/bin:$PATH
EXPOSE 3000 3443

# 🔟 Comanda d'inici
CMD ["node", "/app/src/app.js"]

# -- Estadi final (Només per executar l'app) --
FROM node:20-alpine AS runner

WORKDIR /app

# Ensure node is available in the PATH
ENV PATH=/usr/local/bin:$PATH

# 7️⃣ Copiar només el codi compilat i les dependències de producció
COPY package*.json ./
RUN npm install --only=production
COPY --from=builder /app/dist/src ./src
# Ensure the entry point file exists
RUN ls -l ./src/app.js || (echo "Entry point file not found!" && exit 1)
#COPY ./cert ./cert

# 8️⃣ Definir variables d'entorn
ENV ENTORN=production
ENV MONGODB_URI=mongodb://mongo:27017/mydb
ENV MONGODB_DB=menudb
ENV SERVER_PORT=3000
ENV SERVER_KEY=./cert/server.key
ENV SERVER_CERT=./cert/server.cert

# 9️⃣ Exposar el port
EXPOSE 3000 3443

# 🔟 Comanda d'inici
CMD ["node", "/app/src/app.js"]

