# 1️⃣ Imatge base oficial de Node.js
FROM node:22-alpine AS builder

# 2️⃣ Definir el directori de treball
WORKDIR /app

# 3️⃣ Copiar només els fitxers de dependències per optimitzar la caché
COPY package*.json tsconfig.json ./

# 4️⃣ Instal·lar dependències
RUN npm install

# 5️⃣ Copiar el codi font
COPY ./src ./src

# 6️⃣ Compilar el codi TypeScript
RUN npm run build

# -- Estadi final (Només per executar l'app) --
FROM node:22-alpine AS runner

WORKDIR /app

# 7️⃣ Copiar només el codi compilat i les dependències de producció
COPY package*.json ./
RUN npm install --only=production
COPY --from=builder /app/dist/src ./src
#COPY ./cert ./cert


# 8️⃣ Definir variables d'entorn
ENV ENTORN=production
ENV MONGODB_URI=mongodb://mongo:27017/mydb
ENV MONGODB_DB=menudb
ENV SERVER_PORT=3000
ENV SERVER_KEY=./cert/server.key
ENV SERVER_CERT=./cert/server.cert


# 9️⃣ Exposar el port
EXPOSE 3000 3443

# 🔟 Comanda d'inici
CMD ["node", "./src/app.js"]

