name: CD server/frontend

on:
  workflow_run:
    workflows: ["CI server", "CI Frontend"]
    types:
      - completed

jobs:
  sftp-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download server artifact
      uses: actions/download-artifact@v4
      with:
        name: server-dist


    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-dist


    - name: Install OpenVPN
      run: sudo apt-get update && sudo apt-get install -y openvpn

    - name: Configure and Connect to VPN
      run: sudo openvpn --config ${{ secrets.OPENVPN_CONFIG }} --daemon
      env:
        OPENVPN_USERNAME: ${{ secrets.OPENVPN_USERNAME }}
        OPENVPN_PASSWORD: ${{ secrets.OPENVPN_PASSWORD }}

    - name: Upload via SFTP
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./server-dist/
        remote_path: /remote/path/on/server
        remote_host: ${{ secrets.SFTP_HOST }}
        remote_user: ${{ secrets.SFTP_USER }}
        remote_key: ${{ secrets.SFTP_KEY }}