name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Audit for vulnerabilities
      run: npm audit

    - name: build
      run: npm run build

    - name: save dist folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: frontend/dist
        retention-days: 1

  build-server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install server dependencies
      run: npm install

    - name: Audit for vulnerabilities
      run: npm audit

    - name: run build
      run: npm run build

    - name: save dist folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: server-dist
        path: server/dist
        retention-days: 1

  sftp-upload:
    needs: [build-frontend, build-server]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download server artifact
      uses: actions/download-artifact@v4
      with:
        name: server-dist


    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-dist


    - name: Install OpenVPN
      run: sudo apt-get update && sudo apt-get install -y openvpn

    - name: test openvpn config file
      run: echo "${{ secrets.OPENVPN_CONFIG }}" > /tmp/openvpn.conf 

    - name: Configure and Connect /tmp/openvpn.conf to VPN
      run: sudo openvpn --config /tmp/openvpn.conf --daemon 

    - name: Wait for VPN to connect
      run: sleep 10

    - name: status of VPN
      run: sudo systemctl list-units --type=service | grep openvpn

    - name: test VPN connection
      run:  sudo grep openvpn /var/log/messages

    - name: Upload via SFTP
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./server-dist/
        remote_path: /remote/path/on/server
        remote_host: ${{ secrets.SFTP_HOST }}
        remote_user: ${{ secrets.SFTP_USER }}
        remote_key: ${{ secrets.SFTP_KEY }}
