name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Audit for vulnerabilities
      run: npm audit

    - name: build
      run: npm run build

    - name: save dist folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: frontend/dist
        retention-days: 1

  build-server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install server dependencies
      run: npm install

    - name: Audit for vulnerabilities
      run: npm audit

    - name: run build
      run: npm run build

    - name: save dist folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: server-dist
        path: server/dist
        retention-days: 1

  sftp-upload:
    needs: [build-frontend, build-server]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download server artifact
      uses: actions/download-artifact@v4
      with:
        name: server-dist


    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-dist


    - name: Install OpenVPN
      run: sudo apt-get update && sudo apt-get install -y openvpn

    - name: test openvpn config file
      run: echo "${{ secrets.OPENVPN_CONFIG }}" > /tmp/openvpn.conf 

    - name: Configure and Connect /tmp/openvpn.conf to VPN
      run: sudo openvpn --config /tmp/openvpn.conf --daemon 

    - name: Wait for VPN to connect
      run: sleep 10

    - name: ping server
      run: ping -c 1 10.8.0.1
       
    - name: status of VPN
      run: sudo systemctl list-units --type=service | grep openvpn

    - name: ls server-dist
      run: ls -l server-dist*

    - name: Upload via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        local_path: server-dist.zip
        remote_path: .
        server: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWORD }}
