name: CI Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name change directory
      run: cd frontend

    - name: Set up vue
      uses: actions/setup-vue
      with:
        vue-version: '3.x'

    - name: Install dependencies
      run: npm install


    - name: build
      run: npm run build

    - name: change directory
      run: cd ..

    - name: save dist folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: frontend/dist
        retention-days: 1

